spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: cherrypick-backend

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
