
services:
  nginx:
    image: nginx:1.26.0
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - backend
    depends_on:
      - spring
      - recommender

  spring:
    image: cpdevelopteam/repik:latest
    container_name: spring
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - redis

  recommender:
    image: cpdevelopteam/repik-recommender:latest
    container_name: recommender
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - redis

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge