name: Repik SpringBoot CI/CD

on:
  push:
    branches:
      - release/RP-9

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx (for cache)
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Create .env file from Secrets
        run: echo "${{ secrets.ENV }}" > .env

      - name: Build and Push Docker image (with cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/spring-app:latest
            docker stop spring-app || true
            docker rm spring-app || true
            docker run -d --name spring-app \
              --env-file .env \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/spring-app:latest
