name: Repik SpringBoot CI/CD

on:
  push:
    branches:
      - release/RP-9

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx (for cache)
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and Push Docker image (with cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: cpdevelopteam/repik:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy config/ to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "repik"
          target: "~/"

      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd repik
            echo "${{ secrets.DEV_ENV }}" > spring.env
            docker compose down
            docker compose pull
            docker compose up


